steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['iam', 'service-accounts', 'keys', 'create', './key.json', '--iam-account=devilweb@appspot.gserviceaccount.com']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['appengine:deploy', '-Dappengine.additionalParams=--service_account_json_key_file=./key.json']
timeout: "1600s"