steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['iam', 'service-accounts', 'keys', 'create', './somekey.json', '--iam-account=administrador@devilweb.iam.gserviceaccount.com']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'activate-service-account', --key-file=./somekey.json]
- name: 'gcr.io/cloud-builders/mvn'
  args: ['appengine:deploy']
timeout: "1600s"